
name: CI

# 触发条件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # 虚拟环境
    runs-on: ubuntu-latest

    steps:
    # 获取源码
    - name: Checkout
      uses: actions/checkout@v2
    
    # 使用 node
    # - name: Use node
    #   uses: actions/setup-node@master
    #   with:
    #     node-version: '12'

    # # 安装依赖
    # - name: Install
    #   run: |
    #     cd $GITHUB_WORKSPACE/client && npm install
    #     cd $GITHUB_WORKSPACE/server && npm install

    # # 打包应用
    # - name: Build
    #   run: |
    #     cd $GITHUB_WORKSPACE/client && npm run build
    
    # 上传文件
    - name: Upload
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}} 
        username: ${{secrets.USERNAME}}
        key: ${{secrets.ID_RSA}} 
        source: './'
        target: "Applications/business-card"
    
    # 重启服务
    - name: Restart
      uses: appleboy/ssh-action@master  
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{secrets.ID_RSA}} 
        script: |
        cd ~/Applications/business-card/client && npm install && npm run build