
name: CI

# 触发条件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # 虚拟机环境
    runs-on: ubuntu-latest

    steps:
    # 获取源码
    - name: Checkout
      uses: actions/checkout@v2
    
    # 使用 node
    - name: Use node
      uses: actions/setup-node@master
      with:
        node-version: '12'

    # 安装依赖
    - name: Install
      run: |
        cd $GITHUB_WORKSPACE/client && npm install
        cd $GITHUB_WORKSPACE/server && npm install

    # 打包 Client
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/client && npm run build
    
    # 上传服务器
    - name: Upload
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}} 
        username: ${{secrets.USERNAME}}
        key: ${{secrets.ID_RSA}} 
        source: $GITHUB_WORKSPACE
        target: "test"